# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/FPGA/VHDL/Lab Training/UART/UART_LED/UART_LED.srcs/sources_1/bd/top/ip/top_clk_wiz_0_0/top_clk_wiz_0_0.xci
# IP: The module: 'top_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA/VHDL/Lab Training/UART/UART_LED/UART_LED.gen/sources_1/bd/top/ip/top_clk_wiz_0_0/top_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/FPGA/VHDL/Lab Training/UART/UART_LED/UART_LED.gen/sources_1/bd/top/ip/top_clk_wiz_0_0/top_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/FPGA/VHDL/Lab Training/UART/UART_LED/UART_LED.gen/sources_1/bd/top/ip/top_clk_wiz_0_0/top_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/FPGA/VHDL/Lab Training/UART/UART_LED/UART_LED.srcs/sources_1/bd/top/ip/top_clk_wiz_0_0/top_clk_wiz_0_0.xci
# IP: The module: 'top_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA/VHDL/Lab Training/UART/UART_LED/UART_LED.gen/sources_1/bd/top/ip/top_clk_wiz_0_0/top_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/FPGA/VHDL/Lab Training/UART/UART_LED/UART_LED.gen/sources_1/bd/top/ip/top_clk_wiz_0_0/top_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/FPGA/VHDL/Lab Training/UART/UART_LED/UART_LED.gen/sources_1/bd/top/ip/top_clk_wiz_0_0/top_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
